version: '3'
services:
  app:
    container_name: express-mongodb-rest-api-boilerplate
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - '80:8000'
    volumes: 
      - ./:/usr/src/app
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'