version: '3'
services:
  app:
    container_name: express-mongodb-rest-api-boilerplate
    restart: always
    build: .
    ports:
      - '80:8000'
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'